server:
  port: 8086

spring:
  docker:
    compose:
      file: C:\Users\ELTAJ\Desktop\ms-1\cards\compose.yaml
      enabled: false


  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

