services:
  loans:
    build: "loans/Dockerfile"
    container_name: "loans-ms"
    ports:
      - "8085:0"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-network
  cards:
    build: "cards/Dockerfile"
    container_name: "cards-ms"
    ports:
      - "8086:8086"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-network

  accounts:
    build: "accounts/Dockerfile"
    container_name: "accounts-ms"
    ports:
      - "8088:8088"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-network
  eurka_server:
    build: "eurekaserver/Dockerfile"
    container_name: "eureka_server"
    ports:
      - "8070:8070"
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
    networks:
      - ms-network

  gateway:
    build: "gatewayserver/Dockerfile"
    container_name: "gateway"
    ports:
      - "8086:8086"
    depends_on:
      eurka_server:
        condition: service_healthy

networks:
  ms-network:
    driver: "bridge"
